app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("movies/", include("movie.urls", namespace="movies")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.urls import path
from .views import (
    MovieList,
    MovieDetail,
    MovieCategory,
    MovieLanguage,
    MovieSearch,
    MovieYear,
)

app_name = "movie"
urlpatterns = [
    path("", MovieList.as_view(), name="movie-list"),
    path("category/<str:category>", MovieCategory.as_view(), name="movie-category"),
    path("language/<str:lang>", MovieLanguage.as_view(), name="movie-language"),
    path("search/", MovieSearch.as_view(), name="movie-search"),
    path("year/<int:year>", MovieYear.as_view(), name="movie-year"),
    path("<slug:slug>", MovieDetail.as_view(), name="movie-detail"),
]

core/models.py
from django.db import models
from django.utils.text import slugify

"""
We will use CATEGORY_CHOICES for the sake of this tutorial
But normally, we will make a model to make the choices dynamic
and it's done as below:

class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to='movies') 

Then we will reference it as an FK in the Movie model

"""


CATEGORY_CHOICES = (
    ("action", "ACTION"),
    ("drama", "DRAMA"),
    ("comedy", "COMEDY"),
    ("romance", "ROMANCE"),
)

LANGUAGE_CHOICES = (
    ("english", "ENGLISH"),
    ("arabic", "ARABIC"),
    ("kurdish", "KURDISH"),
    ("germany", "GERMAN"),
)

STATUS_CHOICES = (
    ("RA", "RECENTLY ADDED"),
    ("MW", "MOST WATCHED"),
    ("TR", "TOP RATED"),
)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to="movies")
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=15)
    """models.ForeignKey('Category', on_delete=models.SET_NULL)"""
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=15)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    cast = models.CharField(max_length=100, blank=True, null=True)
    year = models.DateField()
    views_count = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, null=True)
    movie_trailer = models.URLField(default="#")
    created = models.DateTimeField(auto_now_add=True)
    poster = models.ImageField(upload_to="movies/posters", blank=True, null=True)
    # tags =

    # download links

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} ({self.year})"


# watch links

LINK_Choices = (
    ("D", "Download Link"),
    ("W", "Watch Link"),
)


class MovieLink(models.Model):
    movie = models.ForeignKey(
        "Movie", related_name="movie_download_links", on_delete=models.CASCADE
    )
    type = models.CharField(choices=LINK_Choices, max_length=1)
    link = models.URLField()

    def __str__(self):
        return f"{self.movie.title} ({self.type})'s link"

movie/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

from .models import Movie

from django.views.generic import ListView, DetailView


class HomeView(ListView):
    model = Movie
    template_name = "home.html"

movie/views.py
from django.shortcuts import render

from core.models import Movie, MovieLink

from django.views.generic import ListView, DetailView
from django.views.generic.dates import YearArchiveView
from django.views.decorators.clickjacking import xframe_options_exempt


class MovieList(ListView):
    model = Movie
    template_name = "movies/movie_list.html"
    paginate_by = 10


class MovieDetail(DetailView):
    model = Movie
    template_name = "movies/movie_detail.html"

    def get_object(self):
        object = super(MovieDetail, self).get_object()
        object.views_count += 1
        object.save()
        return object

    def get_context_data(self, **kwargs):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        context["links"] = MovieLink.objects.filter(movie=self.get_object())
        context["related_movies"] = Movie.objects.filter(
            category=self.get_object().category
        ).order_by("-created")[0:6]
        print(context["related_movies"])
        print("Hooray")
        return context


class MovieCategory(ListView):
    model = Movie
    template_name = "movies/movie_list.html"
    paginate_by = 5

    def get_queryset(self):
        self.category = self.kwargs["category"]  # "get_object_or_404()"
        # movies =
        return Movie.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super(MovieCategory, self).get_context_data(**kwargs)
        context["movie_category"] = self.category
        return context


class MovieLanguage(ListView):
    model = Movie
    template_name = "movies/movie_list.html"
    paginate_by = 5

    def get_queryset(self):
        self.language = self.kwargs["lang"]  # "get_object_or_404()"
        # movies =
        return Movie.objects.filter(language=self.language)

    def get_context_data(self, **kwargs):
        context = super(MovieLanguage, self).get_context_data(**kwargs)
        context["movie_language"] = self.language
        return context


class MovieSearch(ListView):
    model = Movie
    template_name = "movies/movie_list.html"
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
            # print('Reached')
            # print(query)
            # print(object_list)
        else:
            object_list = self.model.objects.none()
            print("Rejected")
        return object_list


class MovieYear(YearArchiveView):
    queryset = Movie.objects.all()
    template_name = "movies/movie_archive_year.html"
    date_field = "year"
    make_object_list = True
    allow_future = True

    # print(queryset)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Space Between Us</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <!-- Link Swiper's CSS -->
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <!-- Demo styles -->
    <style>

    </style>
</head>

<body>
    <div class="wrapper">

        <header class="header">
            <figure class="logo">
                <a href="/"><img src="{% static 'img/logo.png' %}" alt="Logo"></figure>
            </a>
            <nav class="menu">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a>Genres</a>
                        <ul>
                            <li><a href="{% url 'movies:movie-category' 'action' %}">Action</a></li>
                            <li><a href="{% url 'movies:movie-category' 'comedy' %}">Comedy</a></li>
                            <li><a href="{% url 'movies:movie-category' 'drama' %}">Drama</a></li>
                            <li><a href="{% url 'movies:movie-category' 'romance' %}">Romance</a></li>
                        </ul>
                    </li>
                    <li><a>Year</a>
                        <ul>
                            <li><a href="year.html">2017</a></li>
                            <li><a href="year.html">2016</a></li>
                            <li><a href="year.html">2015</a></li>
                            <li><a href="year.html">2014</a></li>
                        </ul>
                    </li>
                    <li><a>Language</a>
                        <ul>
                            <li><a href="{% url 'movies:movie-language' 'english' %}">English</a></li>
                            <li><a href="{% url 'movies:movie-language' 'kurdish' %}">Kurdish</a></li>
                            <li><a href="{% url 'movies:movie-language' 'arabic' %}">Arabic</a></li>
                            <li><a href="{% url 'movies:movie-language' 'germany' %}">German</a></li>
                        </ul>
                    </li>

                    <li class="mobsearch">
                        <form class="mobform" method="GET" action="{% url 'movies:movie-search' %}">
                            <input type="text" name="query" value="{{ request.GET.q }}" class="mobsearchfield" placeholder="Search...">
                            <input type="submit" value="" class="mobsearchsubmit">
                        </form>
                    </li>
                </ul>
            </nav>
            <form class="search" method="GET" action="{% url 'movies:movie-search' %}">
                <input type="text" name="query" value="{{ request.GET.q }}" class="searchfield" placeholder="Search...">
                <input type="submit" value="" class="searchsubmit">
            </form>

            <div class="toggle"><img src="{% static 'img/menu.svg' %}"></div>
        </header>
        <!-- Swiper -->
        <!--<div class="homeslider">
			<div class="swiper-container">
		

				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="images/slider/poster2.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster1.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 2</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
					<div class="swiper-slide">
						<img src="images/slider/poster2.jpg">
						<div class="caption">
							<div class="captioninside">
								<h3>Movie Title 3</h3>
								<p>Lorem ipsum dolor siamet</p>
								<a href="single.html" class="playbutton">Play</a>
							</div>
						</div>
					</div>
				</div>
				Add Pagination
				<div class="swiper-pagination"></div>
			</div>
		</div>
	-->

        {% block main %} {% endblock %}


        <footer class="footer">
            <div class="copyright">
                <p>Copyright &copy 2017 www.focusoncode.com</p>
            </div>
            <div class="footermenu">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    <li><a href="terms.html">Terms and conditions</a></li>
                </ul>
            </div>
            <div class="tags">
                <ul>
                    <li>Watch Free Movies Trailers</li>
                    <li>Movie Trailers</li>
                    <li>English Subtitled Movies Trailers</li>
                    <li>Latest Movies Trailers</li>
                    <li>New Movies Trailers</li>

                </ul>
            </div>

        </footer>



    </div>
    <!-- Swiper JS -->
    <script src="{% static 'js/swiper.min.js' %}"></script>

    <!-- Initialize Swiper -->
    <script>
        $(document).ready(function() {


            var swiper = new Swiper('.homeslider > .swiper-container', {
                pagination: '.swiper-pagination',
                paginationClickable: true,
                preventClicks: false,
                preventClicksPropagation: false,
                effect: 'fade',
                breakpoints: {
                    320: {
                        height: 200
                    },

                    480: {
                        height: 300
                    },

                    768: {
                        height: 400
                    },
                    1024: {
                        height: 500
                    }
                }
            });

            var recentswiper = new Swiper('.recentslider > .swiper-container', {
                nextButton: '.recent-next',
                prevButton: '.recent-prev',
                slidesPerView: 8,
                paginationClickable: true,
                preventClicks: false,
                preventClicksPropagation: false,
                spaceBetween: 10,
                breakpoints: {
                    320: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    480: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    768: {
                        slidesPerView: 5,
                        spaceBetween: 5
                    },
                    1024: {
                        slidesPerView: 6,
                        spaceBetween: 10
                    }
                }
            });

            var mostswiper = new Swiper('.mostslider > .swiper-container', {
                nextButton: '.most-next',
                prevButton: '.most-prev',
                slidesPerView: 8,
                paginationClickable: true,
                preventClicks: false,
                preventClicksPropagation: false,
                spaceBetween: 10,
                breakpoints: {
                    320: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    480: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    768: {
                        slidesPerView: 5,
                        spaceBetween: 5
                    },
                    1024: {
                        slidesPerView: 6,
                        spaceBetween: 10
                    }
                }
            });

            var topswiper = new Swiper('.topslider > .swiper-container', {
                nextButton: '.top-next',
                prevButton: '.top-prev',
                slidesPerView: 8,
                paginationClickable: true,
                preventClicks: false,
                preventClicksPropagation: false,
                spaceBetween: 10,
                breakpoints: {
                    320: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    480: {
                        slidesPerView: 3,
                        spaceBetween: 5
                    },

                    768: {
                        slidesPerView: 5,
                        spaceBetween: 5
                    },
                    1024: {
                        slidesPerView: 6,
                        spaceBetween: 10
                    }
                }
            });

        });
    </script>
</body>

</html>

templates/movies/movie_archive_year.html
{% extends 'base.html' %} {% load static %} {% block main %}

<main class="content">
    <section class="centered">
        {% if movie_category %}
        <h3>{{movie_category|title}} Movies</h3>
        {% endif %} {% if movie_language %}
        <h3>{{movie_language|title}} Movies</h3>
        {% endif %}
        <div class="movies">
            {% for movie in object_list %}
            <div class="mov">
                <a href="{% url 'movies:movie-detail' movie.slug %}">
                    <img src="{{ movie.image.url}}">
                    <h2 class="movietitle">{{ movie.title }}</h2>
                </a>
            </div>
            {% empty %}
            <div class="movie"></div>
            <h3>There are no movies in this category</h3>
            {% endfor %}
        </div>
        {% if is_paginated %}
        <nav class="pagination">
            <ul>
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                {% else %}
                <li class="disabled"></li>
                {% endif %} {% for page in page_obj.paginator.page_range %} {% if page_obj.number == page %}
                <li><a href="#">{{page}}</a></li>
                {% else %}
                <li><a href="?page={{ page }}">{{page}}</a></li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                {% else %}
                <li class="disabled">></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </section>

</main>

{% endblock %}

templates/movies/movie_detail.html
{% extends 'base.html' %} {% load static %} {% block main %}

<main class="content">
    <div class="single">

        <section class="trailer">
            <h3>Trailer</h3>
            <div class="trailer_frame">
                <iframe width="560" height="315" src="{{object.movie_trailer}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </section>

        <section class="movie">
            <img src="{{object.image.url}}">
            <ul>
                <li>{{object}}</li>
                <li>{{object.description}}</li>
                <li><a href="genre.html">Adventure</a>, <a href="genre.html">Drama</a>, <a href="genre.html">Romance</a></li>
                <li><a href="cast.html">{{object.cast}}</a></a>
                </li>
                <li>{{object.views_count}} Views</li>
            </ul>
        </section>
        <section class="links">
            <h3>Links</h3>
            <ul class="dlinks">
                <li><a>Download</a></li>
                {% for link in links %} {% if link.type == 'D' %}
                <li><a href="{{link.link}}">Link{{forloop.counter}}</a></li>
                {% endif %} {% endfor %}

            </ul>
            <ul class="wlinks">
                <li><a>Watch</a></li>
                {% for link in links %} {% if link.type == 'W' %}
                <li><a href="{{link.link}}">Link{{forloop.counter}}</a></li>
                {% endif %} {% endfor %}
            </ul>
        </section>

        <section class="related">
            <h3>Related movies</h3>
            {% for rm in related_movies %}
            <div class="relatemovie">
                <a href="{% url 'movies:movie-detail' rm.slug %}"><img src="{{rm.image.url}}"></a>
                <a href="{% url 'movies:movie-detail' rm.slug %}"><span class="relatedname">{{rm.title}}</span></a>
            </div>
            {% endfor %}

        </section>

        <section class="comments">
            <h3>Comments</h3>
        </section>
    </div>
</main>
{% endblock %}

templates/movies/movie_list.html
{% extends 'base.html' %} {% load static %} {% block main %}

<main class="content">
    <section class="centered">
        {% if movie_category %}
        <h3>{{movie_category|title}} Movies</h3>
        {% endif %} {% if movie_language %}
        <h3>{{movie_language|title}} Movies</h3>
        {% endif %}
        <div class="movies">
            {% for movie in object_list %}
            <div class="mov">
                <a href="{% url 'movies:movie-detail' movie.slug %}">
                    <img src="{{ movie.image.url}}">
                    <h2 class="movietitle">{{ movie.title }}</h2>
                </a>
            </div>
            {% empty %}
            <div class="movie"></div>
            <h3>There are no movies in this category</h3>
            {% endfor %}
        </div>
        {% if is_paginated %}
        <nav class="pagination">
            <ul>
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                {% else %}
                <li class="disabled"></li>
                {% endif %} {% for page in page_obj.paginator.page_range %} {% if page_obj.number == page %}
                <li><a href="#">{{page}}</a></li>
                {% else %}
                <li><a href="?page={{ page }}">{{page}}</a></li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
                {% else %}
                <li class="disabled">></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </section>

</main>

{% endblock %}